[package]
name = "hackernews-sycamore"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_error_panic_hook = "0.1.6"
console_log = "0.2.0"
log = "0.4.14"
sycamore = { git = "https://github.com/sycamore-rs/sycamore", rev = "a2d7275" }
sycamore-router = { git = "https://github.com/sycamore-rs/sycamore", rev = "a2d7275" }
